<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="create_run_jar" name="Create Runnable Jar for Project kirjaloki2">
    <!--this file was created by Eclipse Runnable JAR Export Wizard-->
    <!--ANT 1.7 is required                                        -->
    <!--define folder properties-->
    <property name="dir.buildfile" value="."/>
    <property name="dir.workspace" value="/Users/heta/opinnot/ohj2/ws"/>
    <property name="dir.jarfile" value="${dir.buildfile}"/>
    <target name="create_run_jar">
        <jar destfile="${dir.jarfile}/kirjaloki.jar" filesetmanifest="mergewithoutmain">
            <manifest>
                <attribute name="Main-Class" value="fxKirjaloki2.Kirjaloki2Main"/>
                <attribute name="Class-Path" value="."/>
            </manifest>
            <fileset dir="${dir.jarfile}/bin"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.fx.ide.css.jfx8_3.8.0.202204150904.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-commons_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-engine_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-launcher_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-runner_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-suite-api_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-suite-engine_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-suite-commons_1.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/junit-vintage-engine_5.14.1.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/org.opentest4j_1.3.0.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/org.apiguardian.api_1.1.2.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/org.junit_4.13.2.v20240929-1000.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Applications/Eclipse.app/Contents/Eclipse/plugins/org.hamcrest_3.0.0.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Users/heta/devel/jar/Music.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Users/heta/devel/jar/Graphics.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Users/heta/devel/jar/Ali.jar"/>
            <zipfileset excludes="META-INF/*.SF" src="/Users/heta/devel/jar/fxgui.jar"/>
        </jar>
    </target>
</project>
