package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.PaivaysTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.19 16:41:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivaysTarkistusTest {


  // Generated by ComTest BEGIN
  /** testTarkistaLukuPvm20 */
  @Test
  public void testTarkistaLukuPvm20() {    // PaivaysTarkistus: 20
    Boolean pvm1 = tarkistaLukuPvm("1.1.2020"); Boolean pvm2 = tarkistaLukuPvm("1.12.2020"); 
    Boolean pvm3 = tarkistaLukuPvm("11.1.2020"); Boolean pvm4 = tarkistaLukuPvm("1/1/2020"); 
    Boolean pvm5 = tarkistaLukuPvm("2020"); Boolean pvm6 = tarkistaLukuPvm(".12"); 
    Boolean pvm7 = tarkistaLukuPvm(" "); Boolean pvm8 = tarkistaLukuPvm("1.2020"); Boolean pvm9 = tarkistaLukuPvm("1"); 
    assertEquals("From: PaivaysTarkistus line: 25", true, pvm1); assertEquals("From: PaivaysTarkistus line: 25", true, pvm2); assertEquals("From: PaivaysTarkistus line: 25", true, pvm3); 
    assertEquals("From: PaivaysTarkistus line: 26", false, pvm4); assertEquals("From: PaivaysTarkistus line: 26", false, pvm5); assertEquals("From: PaivaysTarkistus line: 26", false, pvm6); 
    assertEquals("From: PaivaysTarkistus line: 27", false, pvm7); assertEquals("From: PaivaysTarkistus line: 27", false, pvm8); assertEquals("From: PaivaysTarkistus line: 27", false, pvm9); 
  } // Generated by ComTest END
}