package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 09:48:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivaysTarkistusTest {


  // Generated by ComTest BEGIN
  /** testTarkistaLukuPvm21 */
  @Test
  public void testTarkistaLukuPvm21() {    // PaivaysTarkistus: 21
    PaivaysTarkistus pvm1 = new PaivaysTarkistus(); 
    Boolean pvm11 = pvm1.tarkistaLukuPvm("1.1.2020"); Boolean pvm22 = pvm1.tarkistaLukuPvm("1.12.2020"); 
    Boolean pvm33 = pvm1.tarkistaLukuPvm("11.1.2020"); Boolean pvm44 = pvm1.tarkistaLukuPvm("1/1/2020"); 
    Boolean pvm5 = pvm1.tarkistaLukuPvm("2020"); Boolean pvm6 = pvm1.tarkistaLukuPvm(".12"); 
    Boolean pvm7 = pvm1.tarkistaLukuPvm(" "); Boolean pvm8 = pvm1.tarkistaLukuPvm("1.2020"); 
    Boolean pvm9 = pvm1.tarkistaLukuPvm("1"); 
    assertEquals("From: PaivaysTarkistus line: 28", true, pvm11); assertEquals("From: PaivaysTarkistus line: 28", true, pvm22); assertEquals("From: PaivaysTarkistus line: 28", true, pvm33); 
    assertEquals("From: PaivaysTarkistus line: 29", false, pvm44); assertEquals("From: PaivaysTarkistus line: 29", false, pvm5); assertEquals("From: PaivaysTarkistus line: 29", false, pvm6); 
    assertEquals("From: PaivaysTarkistus line: 30", false, pvm7); assertEquals("From: PaivaysTarkistus line: 30", false, pvm8); assertEquals("From: PaivaysTarkistus line: 30", false, pvm9); 
  } // Generated by ComTest END
}