package kanta.test;
// Generated by ComTest BEGIN
import kirjaloki.Kirja;
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.Kirja;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 09:48:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {


  // Generated by ComTest BEGIN
  /** testInt23 */
  @Test
  public void testInt23() {    // Tietue: 23
    Kirja kirja = new Kirja(); 
    assertEquals("From: Tietue line: 26", 5, kirja.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt35 */
  @Test
  public void testInt35() {    // Tietue: 35
    Kirja kirja = new Kirja(); 
    assertEquals("From: Tietue line: 37", 2, kirja.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString47 */
  @Test
  public void testString47() {    // Tietue: 47
    Kirja kirja = new Kirja(); 
    assertEquals("From: Tietue line: 49", "ala", kirja.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString59 */
  @Test
  public void testString59() {    // Tietue: 59
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    assertEquals("From: Tietue line: 62", "2", kirja.anna(0)); 
    assertEquals("From: Tietue line: 63", "10", kirja.anna(1)); 
    assertEquals("From: Tietue line: 64", "Kalastus", kirja.anna(2)); 
    assertEquals("From: Tietue line: 65", "1949", kirja.anna(3)); 
    assertEquals("From: Tietue line: 66", "22", kirja.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString79 */
  @Test
  public void testString79() {    // Tietue: 79
    Kirja kirja = new Kirja(); 
    assertEquals("From: Tietue line: 81", "aloitusvuosi: Ei kokonaisluku (kissa)", kirja.aseta(3,"kissa")); 
    assertEquals("From: Tietue line: 82", null, kirja.aseta(3,"1940")); 
    assertEquals("From: Tietue line: 83", "h/vko: Ei kokonaisluku (kissa)", kirja.aseta(4,"kissa")); 
    assertEquals("From: Tietue line: 84", null, kirja.aseta(4,"20")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue95 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue95() throws CloneNotSupportedException {    // Tietue: 95
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Object kopio = kirja.clone(); 
    assertEquals("From: Tietue line: 100", kirja.toString(), kopio.toString()); 
    kirja.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Tietue line: 102", false, kopio.toString().equals(kirja.toString())); 
    assertEquals("From: Tietue line: 103", true, kopio instanceof Kirja); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString113 */
  @Test
  public void testString113() {    // Tietue: 113
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    { String _l_=kirja.toString(),_r_="2\\|10\\|Kalastus\\|1949\\|22.*"; if ( !_l_.matches(_r_) ) fail("From: Tietue line: 116" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}