package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.19 12:14:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjalokiTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa34 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa34() throws SailoException {    // Kirjaloki: 34
    Kirjaloki kirjaloki = new Kirjaloki(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); 
    assertEquals("From: Kirjaloki line: 39", 0, kirjaloki.getKirjailijoita()); 
    kirjaloki.lisaa(kytomaki1); assertEquals("From: Kirjaloki line: 40", 1, kirjaloki.getKirjailijoita()); 
    kirjaloki.lisaa(kytomaki2); assertEquals("From: Kirjaloki line: 41", 2, kirjaloki.getKirjailijoita()); 
    kirjaloki.lisaa(kytomaki1); assertEquals("From: Kirjaloki line: 42", 3, kirjaloki.getKirjailijoita()); 
    assertEquals("From: Kirjaloki line: 43", 3, kirjaloki.getKirjailijoita()); 
    assertEquals("From: Kirjaloki line: 44", kytomaki1, kirjaloki.annaKirjailija(0)); 
    assertEquals("From: Kirjaloki line: 45", kytomaki2, kirjaloki.annaKirjailija(1)); 
    assertEquals("From: Kirjaloki line: 46", kytomaki1, kirjaloki.annaKirjailija(2)); 
    try {
    assertEquals("From: Kirjaloki line: 47", kytomaki1, kirjaloki.annaKirjailija(3)); 
    fail("Kirjaloki: 47 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjaloki.lisaa(kytomaki1); assertEquals("From: Kirjaloki line: 48", 4, kirjaloki.getKirjailijoita()); 
    kirjaloki.lisaa(kytomaki1); assertEquals("From: Kirjaloki line: 49", 5, kirjaloki.getKirjailijoita()); 
    try {
    kirjaloki.lisaa(kytomaki1); 
    fail("Kirjaloki: 50 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}