package kirjaloki.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjaloki.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 11:06:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista38 
   * @throws SailoException when error
   */
  @Test
  public void testPoista38() throws SailoException {    // Kirjat: 38
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(); margarita21.vastaaMargarita(2); 
    Kirja margarita11 = new Kirja(); margarita11.vastaaMargarita(1); 
    Kirja margarita22 = new Kirja(); margarita22.vastaaMargarita(2); 
    Kirja margarita12 = new Kirja(); margarita12.vastaaMargarita(1); 
    Kirja margarita23 = new Kirja(); margarita23.vastaaMargarita(2); 
    kirjat.lisaa(margarita21); 
    kirjat.lisaa(margarita11); 
    kirjat.lisaa(margarita22); 
    kirjat.lisaa(margarita12); 
    assertEquals("From: Kirjat line: 51", false, kirjat.poista(margarita23)); assertEquals("From: Kirjat line: 51", 4, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 52", true, kirjat.poista(margarita11)); assertEquals("From: Kirjat line: 52", 3, kirjat.getLkm()); 
    List<Kirja> h = kirjat.annaKirjat(1); 
    assertEquals("From: Kirjat line: 54", 1, h.size()); 
    assertEquals("From: Kirjat line: 55", margarita12, h.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaKirjailijanKirjat70 */
  @Test
  public void testPoistaKirjailijanKirjat70() {    // Kirjat: 70
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(); margarita21.vastaaMargarita(2); 
    Kirja margarita11 = new Kirja(); margarita11.vastaaMargarita(1); 
    Kirja margarita22 = new Kirja(); margarita22.vastaaMargarita(2); 
    Kirja margarita12 = new Kirja(); margarita12.vastaaMargarita(1); 
    Kirja margarita23 = new Kirja(); margarita23.vastaaMargarita(2); 
    kirjat.lisaa(margarita21); 
    kirjat.lisaa(margarita11); 
    kirjat.lisaa(margarita22); 
    kirjat.lisaa(margarita12); 
    kirjat.lisaa(margarita23); 
    assertEquals("From: Kirjat line: 82", 3, kirjat.poistaKirjailijanKirjat(2)); assertEquals("From: Kirjat line: 82", 2, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 83", 0, kirjat.poistaKirjailijanKirjat(3)); assertEquals("From: Kirjat line: 83", 2, kirjat.getLkm()); 
    List<Kirja> h = kirjat.annaKirjat(2); 
    assertEquals("From: Kirjat line: 85", 0, h.size()); 
    h = kirjat.annaKirjat(1); 
    assertEquals("From: Kirjat line: 87", margarita11, h.get(0)); 
    assertEquals("From: Kirjat line: 88", margarita12, h.get(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta123 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta123() throws SailoException {    // Kirjat: 123
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(); kirja1.vastaaMargarita(2); 
    Kirja kirja2 = new Kirja(); kirja2.vastaaMargarita(1); 
    Kirja kirja3 = new Kirja(); kirja3.vastaaMargarita(2); 
    Kirja kirja4 = new Kirja(); kirja4.vastaaMargarita(1); 
    Kirja margarita23 = new Kirja(); margarita23.vastaaMargarita(2); 
    String tiedNimi = "testiheta"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    kirjat.lueTiedostosta(tiedNimi); 
    fail("Kirjat: 135 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja2); 
    kirjat.lisaa(kirja3); 
    kirjat.lisaa(kirja4); 
    kirjat.lisaa(margarita23); 
    kirjat.tallenna(); 
    kirjat = new Kirjat(); 
    kirjat.lueTiedostosta(tiedNimi); 
    Iterator<Kirja> i = kirjat.iterator(); 
    assertEquals("From: Kirjat line: 145", kirja1.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 146", kirja2.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 147", kirja3.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 148", kirja4.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 149", margarita23.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 150", false, i.hasNext()); 
    kirjat.lisaa(margarita23); 
    kirjat.tallenna(); 
    assertEquals("From: Kirjat line: 153", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Kirjat line: 155", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator262 */
  @Test
  public void testIterator262() {    // Kirjat: 262
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(2); kirjat.lisaa(margarita21); 
    Kirja margarita11 = new Kirja(1); kirjat.lisaa(margarita11); 
    Kirja margarita22 = new Kirja(2); kirjat.lisaa(margarita22); 
    Kirja margarita12 = new Kirja(1); kirjat.lisaa(margarita12); 
    Kirja margarita23 = new Kirja(2); kirjat.lisaa(margarita23); 
    Iterator<Kirja> i2=kirjat.iterator(); 
    assertEquals("From: Kirjat line: 274", margarita21, i2.next()); 
    assertEquals("From: Kirjat line: 275", margarita11, i2.next()); 
    assertEquals("From: Kirjat line: 276", margarita22, i2.next()); 
    assertEquals("From: Kirjat line: 277", margarita12, i2.next()); 
    assertEquals("From: Kirjat line: 278", margarita23, i2.next()); 
    try {
    assertEquals("From: Kirjat line: 279", margarita12, i2.next()); 
    fail("Kirjat: 279 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Kirja kirja1:kirjat ) {
    assertEquals("From: Kirjat line: 285", jnrot[n], kirja1.getKirjailijaId()); n++; 
    }
    assertEquals("From: Kirjat line: 288", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjat303 */
  @Test
  public void testAnnaKirjat303() {    // Kirjat: 303
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(2); kirjat.lisaa(margarita21); 
    Kirja margarita11 = new Kirja(1); kirjat.lisaa(margarita11); 
    Kirja margarita22 = new Kirja(2); kirjat.lisaa(margarita22); 
    Kirja margarita12 = new Kirja(1); kirjat.lisaa(margarita12); 
    Kirja margarita23 = new Kirja(2); kirjat.lisaa(margarita23); 
    Kirja margarita51 = new Kirja(5); kirjat.lisaa(margarita51); 
    List<Kirja> loytyneet; 
    loytyneet = kirjat.annaKirjat(3); 
    assertEquals("From: Kirjat line: 316", 0, loytyneet.size()); 
    loytyneet = kirjat.annaKirjat(1); 
    assertEquals("From: Kirjat line: 318", 2, loytyneet.size()); 
    assertEquals("From: Kirjat line: 319", true, loytyneet.get(0) == margarita11); 
    assertEquals("From: Kirjat line: 320", true, loytyneet.get(1) == margarita12); 
    loytyneet = kirjat.annaKirjat(5); 
    assertEquals("From: Kirjat line: 322", 1, loytyneet.size()); 
    assertEquals("From: Kirjat line: 323", true, loytyneet.get(0) == margarita51); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa340 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa340() throws SailoException,CloneNotSupportedException {    // Kirjat: 340
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); 
    assertEquals("From: Kirjat line: 346", 0, kirjat.getLkm()); 
    kirjat.korvaaTaiLisaa(kirja1); assertEquals("From: Kirjat line: 347", 1, kirjat.getLkm()); 
    kirjat.korvaaTaiLisaa(kirja2); assertEquals("From: Kirjat line: 348", 2, kirjat.getLkm()); 
    Kirja kirja3 = kirja1.clone(); 
    kirja3.aseta(2,"kkk"); 
    Iterator<Kirja> i2=kirjat.iterator(); 
    assertEquals("From: Kirjat line: 352", kirja1, i2.next()); 
    kirjat.korvaaTaiLisaa(kirja3); assertEquals("From: Kirjat line: 353", 2, kirjat.getLkm()); 
    i2=kirjat.iterator(); 
    Kirja h = i2.next(); 
    assertEquals("From: Kirjat line: 356", kirja3, h); 
    assertEquals("From: Kirjat line: 357", true, h == kirja3); 
    assertEquals("From: Kirjat line: 358", false, h == kirja1); 
  } // Generated by ComTest END
}