package kirjaloki.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.24 12:46:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjalokiTest {



  // Generated by ComTest BEGIN
  /** testAnnaKirjat47 
 * @throws SailoException mikäli virhe ilmenee*/
  @Test
  public void testAnnaKirjat47() throws SailoException {    // Kirjaloki: 47
    Kirjaloki kirjaloki = new Kirjaloki(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(), kytomaki3 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); kytomaki3.rekisteroi(); 
    int id1 = kytomaki1.getKirjailijaId(); 
    int id2 = kytomaki2.getKirjailijaId(); 
    Kirja margarita11 = new Kirja(id1); kirjaloki.lisaa(margarita11); 
    Kirja margarita12 = new Kirja(id1); kirjaloki.lisaa(margarita12); 
    Kirja margarita21 = new Kirja(id2); kirjaloki.lisaa(margarita21); 
    Kirja margarita22 = new Kirja(id2); kirjaloki.lisaa(margarita22); 
    Kirja margarita23 = new Kirja(id2); kirjaloki.lisaa(margarita23); 
    List<Kirja> loytyneet; 
    loytyneet = kirjaloki.annaKirjat(kytomaki3); 
    assertEquals("From: Kirjaloki line: 63", 0, loytyneet.size()); 
    loytyneet = kirjaloki.annaKirjat(kytomaki1); 
    assertEquals("From: Kirjaloki line: 65", 2, loytyneet.size()); 
    assertEquals("From: Kirjaloki line: 66", true, loytyneet.get(0) == margarita11); 
    assertEquals("From: Kirjaloki line: 67", true, loytyneet.get(1) == margarita12); 
    loytyneet = kirjaloki.annaKirjat(kytomaki2); 
    assertEquals("From: Kirjaloki line: 69", 3, loytyneet.size()); 
    assertEquals("From: Kirjaloki line: 70", true, loytyneet.get(0) == margarita21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa90 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa90() throws SailoException {    // Kirjaloki: 90
    Kirjaloki kirjaloki = new Kirjaloki(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kirjaloki.lisaa(kytomaki1); 
    kirjaloki.lisaa(kytomaki2); 
    kirjaloki.lisaa(kytomaki1); 
    Collection<Kirjailija> loytyneet = kirjaloki.etsi("",-1); 
    Iterator<Kirjailija> it = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 99", kytomaki1, it.next()); 
    assertEquals("From: Kirjaloki line: 100", kytomaki2, it.next()); 
    assertEquals("From: Kirjaloki line: 101", kytomaki1, it.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa113 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa113() throws SailoException {    // Kirjaloki: 113
    Kirjaloki kirjaloki = new Kirjaloki(); 
    Kirjailija kytomaki1 = new Kirjailija(); kytomaki1.vastaaKytomaki(); kytomaki1.rekisteroi(); 
    Kirjailija kytomaki2 = new Kirjailija(); kytomaki2.vastaaKytomaki(); kytomaki2.rekisteroi(); 
    Kirja margarita1 = new Kirja(); margarita1.vastaaMargarita(kytomaki2.getKirjailijaId()); 
    Kirja margarita2 = new Kirja(); margarita2.vastaaMargarita(kytomaki1.getKirjailijaId()); 
    Kirja margarita3 = new Kirja(); margarita3.vastaaMargarita(kytomaki2.getKirjailijaId()); 
    Kirja margarita4 = new Kirja(); margarita4.vastaaMargarita(kytomaki1.getKirjailijaId()); 
    Kirja margarita5 = new Kirja(); margarita5.vastaaMargarita(kytomaki2.getKirjailijaId()); 
    String hakemisto = "testiheta"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/nimet.dat"); 
    File fhtied = new File(hakemisto+"/kirjat.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    kirjaloki.lueTiedostosta(hakemisto); 
    fail("Kirjaloki: 135 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjaloki.lisaa(kytomaki1); 
    kirjaloki.lisaa(kytomaki2); 
    kirjaloki.lisaa(margarita1); 
    kirjaloki.lisaa(margarita2); 
    kirjaloki.lisaa(margarita3); 
    kirjaloki.lisaa(margarita4); 
    kirjaloki.lisaa(margarita5); 
    kirjaloki.tallenna(); 
    kirjaloki = new Kirjaloki(); 
    kirjaloki.lueTiedostosta(hakemisto); 
    Collection<Kirjailija> kaikki = kirjaloki.etsi("",-1); 
    Iterator<Kirjailija> it = kaikki.iterator(); 
    assertEquals("From: Kirjaloki line: 148", kytomaki1, it.next()); 
    assertEquals("From: Kirjaloki line: 149", kytomaki2, it.next()); 
    assertEquals("From: Kirjaloki line: 150", false, it.hasNext()); 
    List<Kirja> loytyneet = kirjaloki.annaKirjat(kytomaki1); 
    Iterator<Kirja> ih = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 153", margarita2, ih.next()); 
    assertEquals("From: Kirjaloki line: 154", margarita4, ih.next()); 
    assertEquals("From: Kirjaloki line: 155", false, ih.hasNext()); 
    loytyneet = kirjaloki.annaKirjat(kytomaki2); 
    ih = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 158", margarita1, ih.next()); 
    assertEquals("From: Kirjaloki line: 159", margarita3, ih.next()); 
    assertEquals("From: Kirjaloki line: 160", margarita5, ih.next()); 
    assertEquals("From: Kirjaloki line: 161", false, ih.hasNext()); 
    kirjaloki.lisaa(kytomaki2); 
    kirjaloki.lisaa(margarita5); 
    kirjaloki.tallenna(); 
    assertEquals("From: Kirjaloki line: 165", true, ftied.delete()); 
    assertEquals("From: Kirjaloki line: 166", true, fhtied.delete()); 
    File fbak = new File(hakemisto+"/nimet.bak"); 
    File fhbak = new File(hakemisto+"/kirjat.bak"); 
    assertEquals("From: Kirjaloki line: 169", true, fbak.delete()); 
    assertEquals("From: Kirjaloki line: 170", true, fhbak.delete()); 
    assertEquals("From: Kirjaloki line: 171", true, dir.delete()); 
  } // Generated by ComTest END
}