package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.04 15:20:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testToString52 */
  @Test
  public void testToString52() {    // Kirja: 52
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Knimistus  | 1949 | 22 t "); 
    assertEquals("From: Kirja line: 55", "2|10|Knimistus|1949|22", kirja.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse69 */
  @Test
  public void testParse69() {    // Kirja: 69
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Knimistus  | 1949 | 22 t "); 
    assertEquals("From: Kirja line: 72", 10, kirja.getKirjailijaId()); 
    assertEquals("From: Kirja line: 73", "2|10|Knimistus|1949|22", kirja.toString()); 
    kirja.rekisteroi(); 
    int n = kirja.getKirjaId(); 
    kirja.parse(""+(n+20)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 79", n+20+1, kirja.getKirjaId()); 
    assertEquals("From: Kirja line: 80", "" + (n+20+1) + "|10|Knimistus|1949|22", kirja.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi172 */
  @Test
  public void testRekisteroi172() {    // Kirja: 172
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 174", 0, kirja1.getKirjaId()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjaId(); 
    int n2 = kirja2.getKirjaId(); 
    assertEquals("From: Kirja line: 180", n2-1, n1); 
  } // Generated by ComTest END
}