package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.04 15:20:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi58 */
  @Test
  public void testGetNimi58() {    // Kirjailija: 58
    Kirjailija kytomaki = new Kirjailija(); 
    kytomaki.vastaaKytomaki(); 
    assertEquals("From: Kirjailija line: 61", "Anni Kytömäki", kytomaki.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi135 */
  @Test
  public void testRekisteroi135() {    // Kirjailija: 135
    Kirjailija kirjailija1 = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 137", 0, kirjailija1.getKirjailijaId()); 
    kirjailija1.rekisteroi(); 
    Kirjailija kirjailija2 = new Kirjailija(); 
    kirjailija2.rekisteroi(); 
    int n1 = kirjailija1.getKirjailijaId(); 
    int n2 = kirjailija2.getKirjailijaId(); 
    assertEquals("From: Kirjailija line: 143", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString176 */
  @Test
  public void testToString176() {    // Kirjailija: 176
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   3  |  Anni Kytömäki   | 1980"); 
    assertEquals("From: Kirjailija line: 179", true, kirjailija.toString().startsWith("3|Anni Kytömäki|1980|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse199 */
  @Test
  public void testParse199() {    // Kirjailija: 199
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   3  |  Anni Kytömäki   | 1980"); 
    assertEquals("From: Kirjailija line: 202", 3, kirjailija.getKirjailijaId()); 
    assertEquals("From: Kirjailija line: 203", true, kirjailija.toString().startsWith("3|Anni Kytömäki|1980|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    kirjailija.rekisteroi(); 
    int n = kirjailija.getKirjailijaId(); 
    kirjailija.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kirjailija.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kirjailija line: 209", n+20+1, kirjailija.getKirjailijaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone233 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone233() throws CloneNotSupportedException {    // Kirjailija: 233
    Kirjailija Kirjailija = new Kirjailija(); 
    Kirjailija.parse("   3  |  Ankka Aku   | 123"); 
    Kirjailija kopio = Kirjailija.clone(); 
    assertEquals("From: Kirjailija line: 238", Kirjailija.toString(), kopio.toString()); 
    Kirjailija.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Kirjailija line: 240", false, kopio.toString().equals(Kirjailija.toString())); 
  } // Generated by ComTest END
}