package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 11:06:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testAnna90 */
  @Test
  public void testAnna90() {    // Kirja: 90
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Margarita  | 1980 | fiktio | 5 | 1.1.2020 | suosikki "); 
    assertEquals("From: Kirja line: 93", "2", kirja.anna(0)); 
    assertEquals("From: Kirja line: 94", "10", kirja.anna(1)); 
    assertEquals("From: Kirja line: 95", "Margarita", kirja.anna(2)); 
    assertEquals("From: Kirja line: 96", "1980", kirja.anna(3)); 
    assertEquals("From: Kirja line: 97", "fiktio", kirja.anna(4)); 
    assertEquals("From: Kirja line: 98", "5", kirja.anna(5)); 
    assertEquals("From: Kirja line: 99", "1.1.2020", kirja.anna(6)); 
    assertEquals("From: Kirja line: 100", "suosikki", kirja.anna(7)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta136 */
  @Test
  public void testAseta136() {    // Kirja: 136
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 138", "Julkaisuvuosi väärin = \"202k\"", kirja.aseta(3,"202k")); 
    assertEquals("From: Kirja line: 139", null, kirja.aseta(3,"1940")); 
    assertEquals("From: Kirja line: 140", "Anna tähdet asteikolla 1-5", kirja.aseta(5,"6")); 
    assertEquals("From: Kirja line: 141", null, kirja.aseta(4,"3")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone198 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone198() throws CloneNotSupportedException {    // Kirja: 198
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Margarita  | 1980 | fiktio | 5 | 1.1.2020 | suosikki "); 
    Kirja kopio = kirja.clone(); 
    assertEquals("From: Kirja line: 203", kirja.toString(), kopio.toString()); 
    kirja.parse("   3   |  10  |   Margarita  | 1980 | fiktio | 5 | 1.1.2020 | suosikki "); 
    assertEquals("From: Kirja line: 205", false, kopio.toString().equals(kirja.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString230 */
  @Test
  public void testToString230() {    // Kirja: 230
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Margarita  | 1980 | fiktio | 5 | 1.1.2020 | suosikki "); 
    assertEquals("From: Kirja line: 233", "2|10|Margarita|1980|fiktio|5|1.1.2020|suosikki", kirja.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse256 */
  @Test
  public void testParse256() {    // Kirja: 256
    Kirja kirja = new Kirja(); 
    kirja.parse("   2   |  10  |   Margarita  | 2020 | fiktio t "); 
    assertEquals("From: Kirja line: 259", 10, kirja.getKirjailijaId()); 
    assertEquals("From: Kirja line: 260", "2|10|Margarita|1949|22", kirja.toString()); 
    kirja.rekisteroi(); 
    int n = kirja.getKirjaId(); 
    kirja.parse(""+(n+20)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 266", n+20+1, kirja.getKirjaId()); 
    assertEquals("From: Kirja line: 267", "" + (n+20+1) + "|10|Margarita|2020|fiktio", kirja.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi353 */
  @Test
  public void testRekisteroi353() {    // Kirja: 353
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 355", 0, kirja1.getKirjaId()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjaId(); 
    int n2 = kirja2.getKirjaId(); 
    assertEquals("From: Kirja line: 361", n2-1, n1); 
  } // Generated by ComTest END
}