package kirjaloki.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjaloki.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.23 21:41:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa59 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa59() throws SailoException {    // Kirjailijat: 59
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    assertEquals("From: Kirjailijat line: 63", 0, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki); assertEquals("From: Kirjailijat line: 64", 1, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki2); assertEquals("From: Kirjailijat line: 65", 2, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki); assertEquals("From: Kirjailijat line: 66", 3, kirjailijat.getLkm()); 
    assertEquals("From: Kirjailijat line: 67", kytomaki, kirjailijat.anna(0)); 
    assertEquals("From: Kirjailijat line: 68", kytomaki2, kirjailijat.anna(1)); 
    assertEquals("From: Kirjailijat line: 69", kytomaki, kirjailijat.anna(2)); 
    assertEquals("From: Kirjailijat line: 70", false, kirjailijat.anna(1) == kytomaki); 
    assertEquals("From: Kirjailijat line: 71", true, kirjailijat.anna(1) == kytomaki2); 
    try {
    assertEquals("From: Kirjailijat line: 72", kytomaki, kirjailijat.anna(3)); 
    fail("Kirjailijat: 72 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjailijat.lisaa(kytomaki); assertEquals("From: Kirjailijat line: 73", 4, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki); assertEquals("From: Kirjailijat line: 74", 5, kirjailijat.getLkm()); 
    try {
    kirjailijat.lisaa(kytomaki); 
    fail("Kirjailijat: 75 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta94 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta94() throws SailoException {    // Kirjailijat: 94
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.vastaaKytomaki(); 
    kytomaki2.vastaaKytomaki(); 
    String hakemisto = "testiheta"; 
    String tiedNimi = hakemisto + "/nimet"; 
    File ftied = new File(tiedNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    kirjailijat.lueTiedostosta(tiedNimi); 
    fail("Kirjailijat: 108 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjailijat.lisaa(kytomaki1); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.tallenna(); 
    kirjailijat = new Kirjailijat();  // Poistetaan vanhat luomalla uusi
    kirjailijat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Kirjailija> i = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 115", kytomaki1, i.next()); 
    assertEquals("From: Kirjailijat line: 116", kytomaki2, i.next()); 
    assertEquals("From: Kirjailijat line: 117", false, i.hasNext()); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.tallenna(); 
    assertEquals("From: Kirjailijat line: 120", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Kirjailijat line: 122", true, fbak.delete()); 
    assertEquals("From: Kirjailijat line: 123", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKirjailijaetIterator235 
   * @throws SailoException when error
   */
  @Test
  public void testKirjailijaetIterator235() throws SailoException {    // Kirjailijat: 235
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); 
    kirjailijat.lisaa(kytomaki1); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.lisaa(kytomaki1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Kirjailija kirjailija:kirjailijat) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+kirjailija.getKirjailijaId()); 
    String tulos = " " + kytomaki1.getKirjailijaId() + " " + kytomaki2.getKirjailijaId() + " " + kytomaki1.getKirjailijaId(); 
    assertEquals("From: Kirjailijat line: 254", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Kirjailija>  i=kirjailijat.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Kirjailija kirjailija = i.next(); 
    ids.append(" " + kirjailija.getKirjailijaId()); 
    }
    assertEquals("From: Kirjailijat line: 262", tulos, ids.toString()); 
    Iterator<Kirjailija>  i=kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 265", true, i.next() == kytomaki1); 
    assertEquals("From: Kirjailijat line: 266", true, i.next() == kytomaki2); 
    assertEquals("From: Kirjailijat line: 267", true, i.next() == kytomaki1); 
    try {
    i.next(); 
    fail("Kirjailijat: 269 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi329 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi329() throws SailoException {    // Kirjailijat: 329
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kirjailija1 = new Kirjailija(); kirjailija1.parse("1|Ankka Aku|030201-115H|Paratiisitie 13|"); 
    Kirjailija kirjailija2 = new Kirjailija(); kirjailija2.parse("2|Ankka Tupu||030552-123B|"); 
    Kirjailija kirjailija3 = new Kirjailija(); kirjailija3.parse("3|Susi Sepe|121237-121V||131313|Perämetsä"); 
    Kirjailija kirjailija5 = new Kirjailija(); kirjailija5.parse("4|Ankka Iines|030245-115V|Ankkakuja 9"); 
    Kirjailija kirjailija4 = new Kirjailija(); kirjailija4.parse("5|Ankka Roope|091007-408U|Ankkakuja 12"); 
    kirjailijat.lisaa(kirjailija1); kirjailijat.lisaa(kirjailija2); kirjailijat.lisaa(kirjailija3); kirjailijat.lisaa(kirjailija5); kirjailijat.lisaa(kirjailija4); 
  } // Generated by ComTest END
}