package kirjaloki.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjaloki.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.04 15:16:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta50 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta50() throws SailoException {    // Kirjat: 50
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(); kirja1.vastaaMargarita(2); 
    Kirja kirja2 = new Kirja(); kirja2.vastaaMargarita(1); 
    Kirja kirja3 = new Kirja(); kirja3.vastaaMargarita(2); 
    Kirja kirja4 = new Kirja(); kirja4.vastaaMargarita(1); 
    Kirja pitsi23 = new Kirja(); pitsi23.vastaaMargarita(2); 
    String tiedNimi = "testiheta"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    kirjat.lueTiedostosta(tiedNimi); 
    fail("Kirjat: 62 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja2); 
    kirjat.lisaa(kirja3); 
    kirjat.lisaa(kirja4); 
    kirjat.lisaa(pitsi23); 
    kirjat.tallenna(); 
    kirjat = new Kirjat(); 
    kirjat.lueTiedostosta(tiedNimi); 
    Iterator<Kirja> i = kirjat.iterator(); 
    assertEquals("From: Kirjat line: 72", kirja1.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 73", kirja2.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 74", kirja3.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 75", kirja4.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 76", pitsi23.toString(), i.next().toString()); 
    assertEquals("From: Kirjat line: 77", false, i.hasNext()); 
    kirjat.lisaa(pitsi23); 
    kirjat.tallenna(); 
    assertEquals("From: Kirjat line: 80", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Kirjat line: 82", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator189 */
  @Test
  public void testIterator189() {    // Kirjat: 189
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(2); kirjat.lisaa(margarita21); 
    Kirja margarita11 = new Kirja(1); kirjat.lisaa(margarita11); 
    Kirja margarita22 = new Kirja(2); kirjat.lisaa(margarita22); 
    Kirja margarita12 = new Kirja(1); kirjat.lisaa(margarita12); 
    Kirja margarita23 = new Kirja(2); kirjat.lisaa(margarita23); 
    Iterator<Kirja> i2=kirjat.iterator(); 
    assertEquals("From: Kirjat line: 201", margarita21, i2.next()); 
    assertEquals("From: Kirjat line: 202", margarita11, i2.next()); 
    assertEquals("From: Kirjat line: 203", margarita22, i2.next()); 
    assertEquals("From: Kirjat line: 204", margarita12, i2.next()); 
    assertEquals("From: Kirjat line: 205", margarita23, i2.next()); 
    try {
    assertEquals("From: Kirjat line: 206", margarita12, i2.next()); 
    fail("Kirjat: 206 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Kirja kirja1:kirjat ) {
    assertEquals("From: Kirjat line: 212", jnrot[n], kirja1.getKirjailijaId()); n++; 
    }
    assertEquals("From: Kirjat line: 215", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjat230 */
  @Test
  public void testAnnaKirjat230() {    // Kirjat: 230
    Kirjat kirjat = new Kirjat(); 
    Kirja margarita21 = new Kirja(2); kirjat.lisaa(margarita21); 
    Kirja margarita11 = new Kirja(1); kirjat.lisaa(margarita11); 
    Kirja margarita22 = new Kirja(2); kirjat.lisaa(margarita22); 
    Kirja margarita12 = new Kirja(1); kirjat.lisaa(margarita12); 
    Kirja margarita23 = new Kirja(2); kirjat.lisaa(margarita23); 
    Kirja margarita51 = new Kirja(5); kirjat.lisaa(margarita51); 
    List<Kirja> loytyneet; 
    loytyneet = kirjat.annaKirjat(3); 
    assertEquals("From: Kirjat line: 243", 0, loytyneet.size()); 
    loytyneet = kirjat.annaKirjat(1); 
    assertEquals("From: Kirjat line: 245", 2, loytyneet.size()); 
    assertEquals("From: Kirjat line: 246", true, loytyneet.get(0) == margarita11); 
    assertEquals("From: Kirjat line: 247", true, loytyneet.get(1) == margarita12); 
    loytyneet = kirjat.annaKirjat(5); 
    assertEquals("From: Kirjat line: 249", 1, loytyneet.size()); 
    assertEquals("From: Kirjat line: 250", true, loytyneet.get(0) == margarita51); 
  } // Generated by ComTest END
}