package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.19 12:09:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi85 */
  @Test
  public void testRekisteroi85() {    // Kirja: 85
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 87", 0, kirja1.getKirjaId()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjaId(); 
    int n2 = kirja2.getKirjaId(); 
    assertEquals("From: Kirja line: 93", n2-1, n1); 
  } // Generated by ComTest END
}