package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.02.19 12:14:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {


  // Generated by ComTest BEGIN
  /** testGetNimi22 */
  @Test
  public void testGetNimi22() {    // Kirjailija: 22
    Kirjailija kytomaki = new Kirjailija(); 
    kytomaki.vastaaKytomaki(); 
    assertEquals("From: Kirjailija line: 25", "Anni Kytömäki", kytomaki.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi66 */
  @Test
  public void testRekisteroi66() {    // Kirjailija: 66
    Kirjailija kirjailija1 = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 68", 0, kirjailija1.getKirjailijaId()); 
    kirjailija1.rekisteroi(); 
    Kirjailija kirjailija2 = new Kirjailija(); 
    kirjailija2.rekisteroi(); 
    int n1 = kirjailija1.getKirjailijaId(); 
    int n2 = kirjailija2.getKirjailijaId(); 
    assertEquals("From: Kirjailija line: 74", n2-1, n1); 
  } // Generated by ComTest END
}