package kirjaloki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 11:06:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testAseta111 */
  @Test
  public void testAseta111() {    // Kirjailija: 111
    Kirjailija kirjailija = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 113", null, kirjailija.aseta(1,"Anni Kytömäki")); 
    { String _l_=kirjailija.aseta(2,"198"),_r_="Tarkista syntymävuosi"; if ( !_l_.matches(_r_) ) fail("From: Kirjailija line: 114" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
    { String _l_=kirjailija.aseta(2,"2600"),_r_="Tarkista syntymävuosi"; if ( !_l_.matches(_r_) ) fail("From: Kirjailija line: 115" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
    assertEquals("From: Kirjailija line: 116", null, kirjailija.aseta(2,"1980")); 
    assertEquals("From: Kirjailija line: 117", null, kirjailija.aseta(3,"kyllä")); 
    assertEquals("From: Kirjailija line: 118", null, kirjailija.aseta(4,"Finlandia-palkittu")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi178 */
  @Test
  public void testGetNimi178() {    // Kirjailija: 178
    Kirjailija kytomaki = new Kirjailija(); 
    kytomaki.vastaaKytomaki(); 
    assertEquals("From: Kirjailija line: 181", "Anni Kytömäki", kytomaki.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi227 */
  @Test
  public void testRekisteroi227() {    // Kirjailija: 227
    Kirjailija kirjailija1 = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 229", 0, kirjailija1.getKirjailijaId()); 
    kirjailija1.rekisteroi(); 
    Kirjailija kirjailija2 = new Kirjailija(); 
    kirjailija2.rekisteroi(); 
    int n1 = kirjailija1.getKirjailijaId(); 
    int n2 = kirjailija2.getKirjailijaId(); 
    assertEquals("From: Kirjailija line: 235", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString268 */
  @Test
  public void testToString268() {    // Kirjailija: 268
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   3  |  Anni Kytömäki   | 1980"); 
    assertEquals("From: Kirjailija line: 271", true, kirjailija.toString().startsWith("3|Anni Kytömäki|1980|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse294 */
  @Test
  public void testParse294() {    // Kirjailija: 294
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   3  |  Anni Kytömäki   | 1980"); 
    assertEquals("From: Kirjailija line: 297", 3, kirjailija.getKirjailijaId()); 
    assertEquals("From: Kirjailija line: 298", true, kirjailija.toString().startsWith("3|Anni Kytömäki|1980|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    kirjailija.rekisteroi(); 
    int n = kirjailija.getKirjailijaId(); 
    kirjailija.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kirjailija.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kirjailija line: 304", n+20+1, kirjailija.getKirjailijaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals320 */
  @Test
  public void testEquals320() {    // Kirjailija: 320
    Kirjailija kirjailija1 = new Kirjailija(); 
    kirjailija1.parse("   3  |  Anni Kytömäki   | 1980"); 
    Kirjailija kirjailija2 = new Kirjailija(); 
    kirjailija2.parse("   3  |  Anni Kytömäki   | 1980"); 
    Kirjailija kirjailija3 = new Kirjailija(); 
    kirjailija3.parse("   3  |  Ankka Aku   | 1981"); 
    assertEquals("From: Kirjailija line: 328", true, kirjailija1.equals(kirjailija2)); 
    assertEquals("From: Kirjailija line: 329", true, kirjailija2.equals(kirjailija1)); 
    assertEquals("From: Kirjailija line: 330", false, kirjailija1.equals(kirjailija3)); 
    assertEquals("From: Kirjailija line: 331", false, kirjailija3.equals(kirjailija2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone354 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone354() throws CloneNotSupportedException {    // Kirjailija: 354
    Kirjailija Kirjailija = new Kirjailija(); 
    Kirjailija.parse("   3  |  Anni Kytömäki   | 1980"); 
    Kirjailija kopio = Kirjailija.clone(); 
    assertEquals("From: Kirjailija line: 359", Kirjailija.toString(), kopio.toString()); 
    Kirjailija.parse("   4  |  Anni Kytövuori   | 1980"); 
    assertEquals("From: Kirjailija line: 361", false, kopio.toString().equals(Kirjailija.toString())); 
  } // Generated by ComTest END
}