package kirjaloki.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjaloki.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 11:06:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijatTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista55 
   * @throws SailoException when error
   */
  @Test
  public void testPoista55() throws SailoException {    // Kirjailijat: 55
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(), kytomaki3 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); kytomaki3.rekisteroi(); 
    int id1 = kytomaki1.getKirjailijaId(); 
    kirjailijat.lisaa(kytomaki1); kirjailijat.lisaa(kytomaki2); kirjailijat.lisaa(kytomaki3); 
    assertEquals("From: Kirjailijat line: 62", 1, kirjailijat.poista(id1+1)); 
    assertEquals("From: Kirjailijat line: 63", null, kirjailijat.annaId(id1+1)); assertEquals("From: Kirjailijat line: 63", 2, kirjailijat.getLkm()); 
    assertEquals("From: Kirjailijat line: 64", 1, kirjailijat.poista(id1)); assertEquals("From: Kirjailijat line: 64", 1, kirjailijat.getLkm()); 
    assertEquals("From: Kirjailijat line: 65", 0, kirjailijat.poista(id1+3)); assertEquals("From: Kirjailijat line: 65", 1, kirjailijat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa93 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa93() throws SailoException {    // Kirjailijat: 93
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(), kytomaki3 = new Kirjailija(); 
    assertEquals("From: Kirjailijat line: 97", 0, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki1); assertEquals("From: Kirjailijat line: 98", 1, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki2); assertEquals("From: Kirjailijat line: 99", 2, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki3); assertEquals("From: Kirjailijat line: 100", 3, kirjailijat.getLkm()); 
    Iterator<Kirjailija> it = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 102", kytomaki1, it.next()); 
    assertEquals("From: Kirjailijat line: 103", kytomaki2, it.next()); 
    assertEquals("From: Kirjailijat line: 104", kytomaki3, it.next()); 
    kirjailijat.lisaa(kytomaki1); assertEquals("From: Kirjailijat line: 105", 4, kirjailijat.getLkm()); 
    kirjailijat.lisaa(kytomaki2); assertEquals("From: Kirjailijat line: 106", 5, kirjailijat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta125 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta125() throws SailoException {    // Kirjailijat: 125
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.vastaaKytomaki(); 
    kytomaki2.vastaaKytomaki(); 
    String hakemisto = "testiheta"; 
    String tiedNimi = hakemisto + "/nimet"; 
    File ftied = new File(tiedNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    kirjailijat.lueTiedostosta(tiedNimi); 
    fail("Kirjailijat: 139 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjailijat.lisaa(kytomaki1); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.tallenna(); 
    kirjailijat = new Kirjailijat();  // Poistetaan vanhat luomalla uusi
    kirjailijat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Kirjailija> i = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 146", kytomaki1, i.next()); 
    assertEquals("From: Kirjailijat line: 147", kytomaki2, i.next()); 
    assertEquals("From: Kirjailijat line: 148", false, i.hasNext()); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.tallenna(); 
    assertEquals("From: Kirjailijat line: 151", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Kirjailijat line: 153", true, fbak.delete()); 
    assertEquals("From: Kirjailijat line: 154", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKirjailijatIterator265 
   * @throws SailoException when error
   */
  @Test
  public void testKirjailijatIterator265() throws SailoException {    // Kirjailijat: 265
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); 
    kirjailijat.lisaa(kytomaki1); 
    kirjailijat.lisaa(kytomaki2); 
    kirjailijat.lisaa(kytomaki1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Kirjailija kirjailija:kirjailijat) // Kokeillaan for-silmukan toimintaa
    ids.append(" " + kirjailija.getKirjailijaId()); 
    String tulos = " " + kytomaki1.getKirjailijaId() + " " + kytomaki2.getKirjailijaId() + " " + kytomaki1.getKirjailijaId(); 
    assertEquals("From: Kirjailijat line: 284", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Kirjailija>  i=kirjailijat.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Kirjailija kirjailija = i.next(); 
    ids.append(" " + kirjailija.getKirjailijaId()); 
    }
    assertEquals("From: Kirjailijat line: 292", tulos, ids.toString()); 
    Iterator<Kirjailija>  i=kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 295", true, i.next() == kytomaki1); 
    assertEquals("From: Kirjailijat line: 296", true, i.next() == kytomaki2); 
    assertEquals("From: Kirjailijat line: 297", true, i.next() == kytomaki1); 
    try {
    i.next(); 
    fail("Kirjailijat: 299 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi359 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi359() throws SailoException {    // Kirjailijat: 359
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kirjailija1 = new Kirjailija(); kirjailija1.parse("1|Testi Kirjailija1|2001|ei|ammatiltaan myös kokki"); 
    Kirjailija kirjailija2 = new Kirjailija(); kirjailija2.parse("2|Testi Kirjailija2||2001|tietokirjailija"); 
    Kirjailija kirjailija3 = new Kirjailija(); kirjailija3.parse("3|Kirjailija Kirjailija1|2003||ei|klassikkokirjailija"); 
    Kirjailija kirjailija4 = new Kirjailija(); kirjailija4.parse("4|Kirjailija Kirjailija2|2003|kyllä|kirjoittaa fiktiota"); 
    Kirjailija kirjailija5 = new Kirjailija(); kirjailija5.parse("5|Kirjailija Kirjailija3|2000|ei|testi"); 
    kirjailijat.lisaa(kirjailija1); kirjailijat.lisaa(kirjailija2); kirjailijat.lisaa(kirjailija3); kirjailijat.lisaa(kirjailija4); kirjailijat.lisaa(kirjailija5); 
    List<Kirjailija> loytyneet; 
    loytyneet = (List<Kirjailija>)kirjailijat.etsi("*s*",1); 
    assertEquals("From: Kirjailijat line: 370", 2, loytyneet.size()); 
    assertEquals("From: Kirjailijat line: 371", true, loytyneet.get(0) == kirjailija1); 
    assertEquals("From: Kirjailijat line: 372", true, loytyneet.get(1) == kirjailija2); 
    loytyneet = (List<Kirjailija>)kirjailijat.etsi("*3*",2); 
    assertEquals("From: Kirjailijat line: 375", 2, loytyneet.size()); 
    assertEquals("From: Kirjailijat line: 376", true, loytyneet.get(0) == kirjailija3); 
    assertEquals("From: Kirjailijat line: 377", true, loytyneet.get(1) == kirjailija4); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId400 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId400() throws SailoException {    // Kirjailijat: 400
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(), kytomaki3 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); kytomaki3.rekisteroi(); 
    int id1 = kytomaki1.getKirjailijaId(); 
    kirjailijat.lisaa(kytomaki1); kirjailijat.lisaa(kytomaki2); kirjailijat.lisaa(kytomaki3); 
    assertEquals("From: Kirjailijat line: 407", true, kirjailijat.annaId(id1  ) == kytomaki1); 
    assertEquals("From: Kirjailijat line: 408", true, kirjailijat.annaId(id1+1) == kytomaki2); 
    assertEquals("From: Kirjailijat line: 409", true, kirjailijat.annaId(id1+2) == kytomaki3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId424 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId424() throws SailoException {    // Kirjailijat: 424
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(), kytomaki3 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); kytomaki3.rekisteroi(); 
    int id1 = kytomaki1.getKirjailijaId(); 
    kirjailijat.lisaa(kytomaki1); kirjailijat.lisaa(kytomaki2); kirjailijat.lisaa(kytomaki3); 
    assertEquals("From: Kirjailijat line: 431", 1, kirjailijat.etsiId(id1+1)); 
    assertEquals("From: Kirjailijat line: 432", 2, kirjailijat.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa448 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa448() throws SailoException,CloneNotSupportedException {    // Kirjailijat: 448
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija kytomaki1 = new Kirjailija(), kytomaki2 = new Kirjailija(); 
    kytomaki1.rekisteroi(); kytomaki2.rekisteroi(); 
    assertEquals("From: Kirjailijat line: 454", 0, kirjailijat.getLkm()); 
    kirjailijat.korvaaTaiLisaa(kytomaki1); assertEquals("From: Kirjailijat line: 455", 1, kirjailijat.getLkm()); 
    kirjailijat.korvaaTaiLisaa(kytomaki2); assertEquals("From: Kirjailijat line: 456", 2, kirjailijat.getLkm()); 
    Kirjailija kytomaki3 = kytomaki1.clone(); 
    kytomaki3.aseta(3,"kkk"); 
    Iterator<Kirjailija> it = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 460", true, it.next() == kytomaki1); 
    kirjailijat.korvaaTaiLisaa(kytomaki3); assertEquals("From: Kirjailijat line: 461", 2, kirjailijat.getLkm()); 
    it = kirjailijat.iterator(); 
    Kirjailija j0 = it.next(); 
    assertEquals("From: Kirjailijat line: 464", kytomaki3, j0); 
    assertEquals("From: Kirjailijat line: 465", true, j0 == kytomaki3); 
    assertEquals("From: Kirjailijat line: 466", false, j0 == kytomaki1); 
  } // Generated by ComTest END
}