package kirjaloki.test;
// Generated by ComTest BEGIN
import kirjaloki.SailoException;
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kirjaloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2026.03.13 11:06:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjalokiTest {


  // Generated by ComTest BEGIN  // Kirjaloki: 13
   private Kirjaloki kirjaloki; 
   private Kirjailija kytomaki1; 
   private Kirjailija kytomaki2; 
   private int jid1; 
   private int jid2; 
   private Kirja margarita21; 
   private Kirja margarita11; 
   private Kirja margarita22; 
   private Kirja margarita12; 
   private Kirja margarita23; 

   public void alustaKirjaloki() {
     kirjaloki = new Kirjaloki(); 
     kytomaki1 = new Kirjailija(); kytomaki1.vastaaKytomaki(); kytomaki1.rekisteroi(); 
     kytomaki2 = new Kirjailija(); kytomaki2.vastaaKytomaki(); kytomaki2.rekisteroi(); 
     jid1 = kytomaki1.getKirjailijaId(); 
     jid2 = kytomaki2.getKirjailijaId(); 
     margarita21 = new Kirja(jid2); margarita21.vastaaMargarita(jid2); 
     margarita11 = new Kirja(jid1); margarita11.vastaaMargarita(jid1); 
     margarita22 = new Kirja(jid2); margarita22.vastaaMargarita(jid2); 
     margarita12 = new Kirja(jid1); margarita12.vastaaMargarita(jid1); 
     margarita23 = new Kirja(jid2); margarita23.vastaaMargarita(jid2); 
     try {
     kirjaloki.lisaa(kytomaki1); 
     kirjaloki.lisaa(kytomaki2); 
     kirjaloki.lisaa(margarita21); 
     kirjaloki.lisaa(margarita11); 
     kirjaloki.lisaa(margarita22); 
     kirjaloki.lisaa(margarita12); 
     kirjaloki.lisaa(margarita23); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista61 
   * @throws Exception when error
   */
  @Test
  public void testPoista61() throws Exception {    // Kirjaloki: 61
    alustaKirjaloki(); 
    assertEquals("From: Kirjaloki line: 64", 2, kirjaloki.etsi("*",0).size()); 
    assertEquals("From: Kirjaloki line: 65", 2, kirjaloki.annaKirjat(kytomaki1).size()); 
    assertEquals("From: Kirjaloki line: 66", 1, kirjaloki.poista(kytomaki1)); 
    assertEquals("From: Kirjaloki line: 67", 1, kirjaloki.etsi("*",0).size()); 
    assertEquals("From: Kirjaloki line: 68", 0, kirjaloki.annaKirjat(kytomaki1).size()); 
    assertEquals("From: Kirjaloki line: 69", 3, kirjaloki.annaKirjat(kytomaki2).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaKirja83 
   * @throws Exception when error
   */
  @Test
  public void testPoistaKirja83() throws Exception {    // Kirjaloki: 83
    alustaKirjaloki(); 
    assertEquals("From: Kirjaloki line: 86", 2, kirjaloki.annaKirjat(kytomaki1).size()); 
    kirjaloki.poistaKirja(margarita11); 
    assertEquals("From: Kirjaloki line: 88", 1, kirjaloki.annaKirjat(kytomaki1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi105 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testEtsi105() throws CloneNotSupportedException, SailoException {    // Kirjaloki: 105
    alustaKirjaloki(); 
    Kirjailija kirjailija3 = new Kirjailija(); kirjailija3.rekisteroi(); 
    kirjailija3.aseta(1,"Kytömäki Anni"); 
    kirjaloki.lisaa(kirjailija3); 
    Collection<Kirjailija> loytyneet = kirjaloki.etsi("*Kytömäki*",1); 
    assertEquals("From: Kirjaloki line: 112", 1, loytyneet.size()); 
    Iterator<Kirjailija> it = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 114", true, it.next() == kirjailija3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaKirjat140 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaKirjat140() throws SailoException {    // Kirjaloki: 140
    alustaKirjaloki(); 
    Kirjailija kytomaki3 = new Kirjailija(); 
    kytomaki3.rekisteroi(); 
    kirjaloki.lisaa(kytomaki3); 
    List<Kirja> loytyneet; 
    loytyneet = kirjaloki.annaKirjat(kytomaki3); 
    assertEquals("From: Kirjaloki line: 148", 0, loytyneet.size()); 
    loytyneet = kirjaloki.annaKirjat(kytomaki1); 
    assertEquals("From: Kirjaloki line: 150", 2, loytyneet.size()); 
    assertEquals("From: Kirjaloki line: 151", true, loytyneet.get(0) == margarita11); 
    assertEquals("From: Kirjaloki line: 152", true, loytyneet.get(1) == margarita12); 
    loytyneet = kirjaloki.annaKirjat(kytomaki2); 
    assertEquals("From: Kirjaloki line: 154", 3, loytyneet.size()); 
    assertEquals("From: Kirjaloki line: 155", true, loytyneet.get(0) == margarita21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa175 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa175() throws SailoException {    // Kirjaloki: 175
    alustaKirjaloki(); 
    assertEquals("From: Kirjaloki line: 178", 2, kirjaloki.etsi("*",0).size()); 
    kirjaloki.lisaa(kytomaki1); 
    assertEquals("From: Kirjaloki line: 180", 3, kirjaloki.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta200 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta200() throws SailoException {    // Kirjaloki: 200
    String hakemisto = "testiheta"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/nimet.dat"); 
    File fhtied = new File(hakemisto+"/kirjat.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    kirjaloki = new Kirjaloki();  // tiedostoja ei ole, tulee poikkeus 
    try {
    kirjaloki.lueTiedostosta(hakemisto); 
    fail("Kirjaloki: 213 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    alustaKirjaloki(); 
    kirjaloki.setTiedosto(hakemisto);  // nimi annettava koska uusi poisti sen
    kirjaloki.tallenna(); 
    kirjaloki = new Kirjaloki(); 
    kirjaloki.lueTiedostosta(hakemisto); 
    Collection<Kirjailija> kaikki = kirjaloki.etsi("",-1); 
    Iterator<Kirjailija> it = kaikki.iterator(); 
    assertEquals("From: Kirjaloki line: 221", kytomaki1, it.next()); 
    assertEquals("From: Kirjaloki line: 222", kytomaki2, it.next()); 
    assertEquals("From: Kirjaloki line: 223", false, it.hasNext()); 
    List<Kirja> loytyneet = kirjaloki.annaKirjat(kytomaki1); 
    Iterator<Kirja> ih = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 226", false, ih.hasNext()); 
    loytyneet = kirjaloki.annaKirjat(kytomaki2); 
    ih = loytyneet.iterator(); 
    assertEquals("From: Kirjaloki line: 229", false, ih.hasNext()); 
    kirjaloki.lisaa(kytomaki2); 
    kirjaloki.tallenna();  // tekee molemmista .bak
    assertEquals("From: Kirjaloki line: 232", true, ftied.delete()); 
    assertEquals("From: Kirjaloki line: 233", true, fhtied.delete()); 
    File fbak = new File(hakemisto+"/nimet.bak"); 
    File fhbak = new File(hakemisto+"/kirjat.bak"); 
    assertEquals("From: Kirjaloki line: 236", true, fbak.delete()); 
    assertEquals("From: Kirjaloki line: 237", true, fhbak.delete()); 
    assertEquals("From: Kirjaloki line: 238", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa279 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa279() throws SailoException {    // Kirjaloki: 279
    alustaKirjaloki(); 
    assertEquals("From: Kirjaloki line: 282", 2, kirjaloki.etsi("*",0).size()); 
    kirjaloki.lisaa(kytomaki1); 
    assertEquals("From: Kirjaloki line: 284", 2, kirjaloki.etsi("*",0).size()); 
  } // Generated by ComTest END
}